### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Photonios**

### CODE REVIEW

**Comment by warmwaffles** [comment]
Hey @Photonios this commit b70d239 breaks my application. I have to stop using the default manager because it aliased `_new` to an annotated column that I put in.

**Comment by Photonios** [comment]
Thanks for the heads up! I am going to figure out a fix or roll it back in the next release somehow.

**Comment by warmwaffles** [comment]
@Photonios here is a brief example

```python
class SomeReport(PostgresPartitionedModel):
    class PartitioningMeta:
        method = PostgresPartitioningMethod.RANGE
        key = ["report_date"]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    account = models.ForeignKey(to=Account, on_delete=models.DO_NOTHING)
    report_date = models.DateField()
    metric = models.IntegerField()

# ...

result = AmsCampaignReport.objects.filter(
    account__in=some_set_of_accounts,
    report_date__range=(start, stop)
).values(
    "account_id",
    date=F("report_date")
).annotate(
    total_metric=Sum(F("cost"))
).all()

# {"account_id": xxxx, "date": "2020-10-01", "total_metric_new": 123}
# vs before this used to be
# {"account_id": xxxx, "date": "2020-10-01", "total_metric": 123}
```

**Comment by Photonios** [comment]
Hi!

Thanks for the example. Could you tell me the Django and Postgres version you're using?

I also noticed that in your example: `total_metric=Sum(F("cost"))` `cost` is not defined anywhere.

**Comment by warmwaffles** [comment]
@Photonios We are using postgres 11 and django 3.0

I've updated the example. Sorry it was some cut and paste issue that the `cost` snuck in.

**Comment by Photonios** [comment]
@warmwaffles Sorry for the delay on this.

I've reproduced your example as a test, but I cannot confirm the issue you're describing: https://github.com/SectorLabs/django-postgres-extra/pull/116

The tests pass on all Python and Django versions (from Python 3.5 to 3.9, Django 2.0 to 3.1).

Could you show me how to adjust the test I linked to reproduce the problem you're describing?

**Comment by DanielAlderman** [comment]
@Photonios I am getting a similar issue as @warmwaffles, but agree with you that it isn't always present.

I'm running Postgres 10.14 and Django 3.1.

In my experience this bug happens when I introduce a Case object.

```
class MainJobDetail(models.Model):
    required_time = models.DateTimeField()

with postgres_manager(MainJobDetail) as mjd:
    working = mjd.annotate(hour = ExtractHour('required_time')).first()
    print(working.hour)
    not_working = MJmjdD.annotate(hour = ExtractHour('required_time'), slot_order = Case(When(Q(hour__lt = 7), then=Value('0')),default=Value('1'), output_field=CharField())).first()
    print(not_working.hour)
```
 I get the value as intended for `working`, but I get `django.core.exceptions.FieldError: Cannot resolve keyword 'hour' into field. Choices are: hour_new, required_time` on `not_working`

I hope this makes sense and helps you to replicate the issue.

**Comment by Photonios** [comment]
Hi @DanielAlderman! Thanks for the extra details.

Could you post the contents of the `ExtractHour` annotation? I suspect that might have something to do with it.

**Comment by Photonios** [comment]
@warmwaffles @DanielAlderman With the help of @DanielAlderman 's example, I managed to reproduce the issue and I've fixed it in this commit:

https://github.com/SectorLabs/django-postgres-extra/commit/96fd08bbaefc7a0afb73727eca997db586e6e2b5

I've released this fix in `v2.0.3rc1`, on both Github and PyPi: https://github.com/SectorLabs/django-postgres-extra/releases/tag/v2.0.3rc1

Please give this version a shot and let me know if you still have trouble.

**Comment by DanielAlderman** [comment]
Hi @Photonios 

Thanks for looking at this so quickly, I've installed `v.2.0.3rc1` and can confirm I am no longer getting the error.

**Pull request merged**
