### PR TITLE
Add missing semicola to examples in docs.

### PR DESCRIPTION
**Pull request by trifle**
Hi,
thanks for django-postgres-extra, which seems extremely useful.
I noticed that the examples in the docs are missing a couple of semicolons and added them.
This is a totally trivial change :)

### CODE REVIEW

**Comment by Photonios** [comment]
Thanks for the contribution! Could you add some tests for the changes,

**Comment by trifle** [comment]
Hi @Photonios, sorry, I was out of the loop with a cold. I'll try to find time to write tests if possible, but can't promise it'll be soon. Cheers!

**Comment by Photonios** [comment]
@trifle no problem. I'll leave this pull request open till then :) Thanks for the update.

**Comment by anpr** [comment]
One point to bear in mind is that just returning the ids from a `bulk_insert` is not that useful, because only the actually inserted rows return the id, so you don't know to which dict in the input it refers to.

**Comment by trifle** [comment]
@anpr that's a good observation. I also ended up doing a query on all submitted values, not only the successful inserts. Still, I guess it's a good addition to have,  
(a) in case your app doesn't have all the state at hand and wants to know what was updated and
(b) because the API naming suggests that it returns _multiple_ values and it's good not to surprise people.  

Now if only I found the time for those tests ... ;)

**Comment by Photonios** [comment]
I am closing this due to inactivity. Feel free to re-open 😄

**Pull request closed without merging**
