### PR TITLE
Add CI support for Django 3.2

### PR DESCRIPTION
**Pull request by adamantike**
* Update Tox to run with Django 3.2.
* Silence pytest warning regarding junit_family setting.
* Only configure `default_app_config` in Django 3.1 and older. [0]
* Fix fake Django app name, which starts failing in Django 3.2 when the name is not a valid Python identifier.

[0] https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery

### CODE REVIEW

**Comment by adamantike** [comment]
Bump! cc @Photonios

**Comment by Photonios** [comment]
This had some conflicts with other PR's that were open. I've cherry-picked your changes and resolved the conflicts. Thanks for your contribution and sorry for the delay :)

**Comment by Photonios** [comment]
This has been released in v2.0.4rc1.

**Comment by adamantike** [comment]
Thanks a lot, glad to see support for Django 3.2 merged!

**Pull request closed without merging**
