### PR TITLE
Add space before returning statement to prevent invalid syntax

### PR DESCRIPTION
**Pull request by theikkila**
Fixes issue with filtered updates.

### CODE REVIEW

**Comment by Photonios** [comment]
Hi! First of all, thanks for submitting the PR, it's appreciated!

Could you describe in more detail the issue you are experiencing?

**Comment by theikkila** [comment]
@Photonios see issue #22

**Comment by Photonios** [comment]
Aha! Got it! I just reproduced it locally. Any chance you can add a very simple test case to make sure it doesn't break again? See the existing test case `test_query_set_update` in `tests/test_signals.py`.

It seems this only happens with boolean values, or any value that doesn't require wrapping it in quotes. The existing test case doesn't cover. A new one should do the trick, aka `test_query_set_update_boolean` w/e.

**Comment by theikkila** [comment]
@Photonios sure thing, testing that in https://github.com/SectorLabs/django-postgres-extra/pull/21/commits/2da4b06df8e140262ef888a2c65cdd7ef6bec04a

**Comment by Photonios** [comment]
You rock! Thanks, merging it :-) Happy coding!

**Comment by Photonios** [comment]
Released in: https://github.com/SectorLabs/django-postgres-extra/releases/tag/v1.12

It's on PyPi.

**Pull request merged**
